version: '3.9'
services:
  web:
    image: ubuntu/apache2:latest
    build:
      context: ./dockerfiles
      dockerfile: apache.dockerfile
      args:
        - APACHE_EXTENSIONS=${APACHE_EXTENSIONS}
    ports:
      - 80:80
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/apache/wildcard.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - php
  php:
    image: php:${PHP_VERSION}-fpm
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - WORKDIR=${WORKDIR}
        - PHP_VERSION=${PHP_VERSION}
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - TYP=fpm
      target: fpm
    expose:
      - 9000
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/php:/usr/local/etc/php/conf.d/php_ini_files
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - ~/.composer:/root/.composer/
      - ./data/php/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf # Mount FPM config that runs FPM as root
    command: php-fpm -R
  cli:
    image: php:${PHP_VERSION}-cli
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      target: cli
      args:
        - BASH_EXTENSIONS=${BASH_EXTENSIONS}
        - PHP_VERSION=${PHP_VERSION}
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - TYP=cli
        - NODE_VERSION=${NODE_VERSION}
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/php:/usr/local/etc/php/conf.d/php_ini_files
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - ~/.composer:/root/.composer/
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80