version: '3'
services:
  web:
    image: ubuntu/apache2:latest
    build:
      context: ./dockerfiles
      dockerfile: web.dockerfile
      args:
        - APACHE_EXTENSIONS=${APACHE_EXTENSIONS}
        - USERNAME=${USERNAME}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/apache/wildcard.conf:/etc/apache2/sites-available/000-default.conf
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
        host.docker.internal: host-gateway
  php-8.0:
    image: php:8.0-fpm
    build: 
      context: ./dockerfiles
      dockerfile: fpm.dockerfile
      args:
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - PHP_VERSION=8.0
        - USERNAME=${USERNAME}
    user: ${UID}:${GID}
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000
    extra_hosts:
      host.docker.internal: host-gateway
  php-8.1:
    image: php:8.1-fpm
    build: 
      context: ./dockerfiles
      dockerfile: fpm.dockerfile
      args:
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - PHP_VERSION=8.1
        - USERNAME=${USERNAME}
    user: ${UID}:${GID}
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000
    extra_hosts:
      host.docker.internal: host-gateway
  php-8.2:
    image: php:8.2-fpm
    build: 
      context: ./dockerfiles
      dockerfile: fpm.dockerfile
      args:
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - PHP_VERSION=8.2
        - USERNAME=${USERNAME}
    user: ${UID}:${GID}
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000
    extra_hosts:
      host.docker.internal: host-gateway
  cli:
    image: php:${PHP_VERSION}-cli
    build: 
      context: ./dockerfiles
      dockerfile: cli.dockerfile
      args:
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - PHP_VERSION=${PHP_VERSION}
        - BASH_EXTENSIONS=${BASH_EXTENSIONS}
        - NODE_VERSION=${NODE_VERSION}
        - USERNAME=${USERNAME}
    user: ${UID}:${GID}
    volumes:
     - ~/.ssh:/home/${USERNAME}/.ssh
     - ~/.gitconfig:/home/${USERNAME}/.gitconfig
     - ${WORKDIR}:/var/www/html/
     - ./data/php/php.ini:/usr/local/etc/php/php.ini
     - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
        host.docker.internal: host-gateway
    networks:
      lamp:
        ipv4_address: ${IPV4}
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
networks:
  lamp:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24