services:
  web:
    image: ubuntu/apache2:latest
    build:
      context: ./dockerfiles
      dockerfile: web.dockerfile
      args:
        - APACHE_EXTENSIONS=${APACHE_EXTENSIONS}
        - USERNAME=${USERNAME}
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/apache/wildcard.conf:/etc/apache2/sites-available/000-default.conf
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./sock:/sock
    ports:
      - 80:80
    stop_grace_period: 0.3s
  php-8.0:
    image: php:8.0-fpm-alpine
    build: 
      context: ./dockerfiles
      dockerfile: fpm.dockerfile
      args:
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - PHP_VERSION=8.0
        - USERNAME=${USERNAME}
    user: ${UID}:${GID}
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./sock/8.0:/sock
  php-8.1:
    image: php:8.1-fpm-alpine
    build: 
      context: ./dockerfiles
      dockerfile: fpm.dockerfile
      args:
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - PHP_VERSION=8.1
        - USERNAME=${USERNAME}
    user: ${UID}:${GID}
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./sock/8.1:/sock
  php-8.2:
    image: php:8.2-fpm-alpine
    build: 
      context: ./dockerfiles
      dockerfile: fpm.dockerfile
      args:
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - PHP_VERSION=8.2
        - USERNAME=${USERNAME}
    user: ${UID}:${GID}
    volumes:
      - ${WORKDIR}:/var/www/html/
      - ./data/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/php/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./data/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./sock/8.2:/sock
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - 3306:3306